#!/usr/bin/env bash
# Small isolated compatibility smoke, NOT a throughput benchmark.
set -euo pipefail
ENGINE_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
PD_ROOT=/homes/siqic/slime/examples/pd
export PD_ENV_BIN=/homes/siqic/anaconda3/envs/pd/bin
export PATH="${PD_ENV_BIN}:${PATH}"
export SGLANG_OVERLAY_ROOT="${VALIDATION_ENGINE_ROOT:-${ENGINE_ROOT}}/python"
export PD_RUN_QWEN_SCRIPT="${ENGINE_ROOT}/validation/run_pd_servers.sh"
export PYTHONPATH="${SGLANG_OVERLAY_ROOT}:${PD_ROOT}:${PYTHONPATH:-}"
export PYTHONDONTWRITEBYTECODE=1
export RUN_DIR="${RUN_DIR:?Set a fresh isolated RUN_DIR}"
mkdir -p "${RUN_DIR}"
CONTROL_DIR="$(mktemp -d /dev/shm/pd-q35-current-smoke.XXXXXX)"
export PD_P_READY_DIR="${CONTROL_DIR}/ready"
mkdir -p "${PD_P_READY_DIR}"
ln -s "${PD_P_READY_DIR}" "${RUN_DIR}/ready"
export SGLANG_AGENTIC_KV_LEDGER_PATH="${CONTROL_DIR}/lifecycle.json"
export SGLANG_AGENTIC_KV_STAGING_LEDGER_PATH="${CONTROL_DIR}/host.json"
export SGLANG_AGENTIC_KV_P2D_STAGING_LEDGER_PATH="${CONTROL_DIR}/p2d-host.json"
export MODEL_PATH="${MODEL_PATH:-/homes/siqic/Qwen3.5-9B}"
export PREFILL_GPUS="${PREFILL_GPUS:-0}" DECODE_GPUS="${DECODE_GPUS:-1}"
export PREFILL_GPU_GROUPS="${PREFILL_GPU_GROUPS:-0}" DECODE_GPU_GROUPS="${DECODE_GPU_GROUPS:-1}"
export PREFILL_PORTS="${PREFILL_PORTS:-29400}" DECODE_PORTS="${DECODE_PORTS:-29401}" BOOTSTRAP_PORTS="${BOOTSTRAP_PORTS:-29402}"
export ROUTER_PORT="${ROUTER_PORT:-29403}" ROUTER_PROMETHEUS_PORT="${ROUTER_PROMETHEUS_PORT:-29404}" AGENTIC_DIRECT_BASE_PORT="${AGENTIC_DIRECT_BASE_PORT:-29500}"
export PREFILL_TP_SIZE="${PREFILL_TP_SIZE:-1}" DECODE_TP_SIZE="${DECODE_TP_SIZE:-1}"
export PD_LATE_BIND_NUMA_DOMAINS=0
export SGLANG_PD_LATE_BIND_DYNAMIC_PREFILL_DOMAINS=0
export SGLANG_PD_LATE_BIND_GLOBAL_DECODE=0
export PD_SERVE_ONLY=1 PD_SKIP_SEARCH=1
export MEM_FRACTION_STATIC=0.60 DECODE_MEM_FRACTION_STATICS=0.60
export MAX_CONTEXT_LENGTH=8192 MAX_RESPONSE_LENGTH=256
# Deterministic Triton admission requires a whole 4096-token alignment tile.
export PREFILL_CHUNKED_PREFILL_SIZE=4096 PREFILL_MAX_PREFILL_TOKENS=4096
export PD_PAGE_SIZE=64 MAMBA_TRACK_INTERVAL=64
export PD_DETERMINISTIC_INFERENCE=1 PD_SERVER_RANDOM_SEED=2026
export SGLANG_AGENTIC_KV_DEBUG_DIGEST="${SGLANG_AGENTIC_KV_DEBUG_DIGEST:-1}"
export SGLANG_AGENTIC_KV_MAMBA_PROMPT_CHECKPOINT=false
export SGLANG_AGENTIC_KV_CUSTOM_STORAGE_ONLY=true
export D2P_HOST_ARENA_GIB_PER_P=2 P2D_HOST_ARENA_GIB_PER_P=2
export SGLANG_AGENTIC_KV_REGISTER_WINDOW_GIB=1 SGLANG_AGENTIC_KV_REGISTER_CACHE_GIB=4
export SGLANG_AGENTIC_KV_SHARED_HOST_ARENA_BACKEND=memfd
export SGLANG_AGENTIC_KV_P2D_HOST_ARENA_BACKEND=memfd
export FAST_TOOL_THRESHOLD_SECONDS=1 DIRECT_WAIT_SECONDS=1
export SGLANG_AGENTIC_KV_EARLY_CLAIM_POST_TIMEOUT=1
export SGLANG_AGENTIC_KV_SLOW_CONGESTION_RECOMPUTE=true
export MAX_PREFILL_INFLIGHT=4 D_TARGET_KV_FRACTION=0.90
export P_H2D_MAX_INFLIGHT=2 D2H_ACTIVE_SNAPSHOTS=2
export P2D_D2H_HOST_COPY_WORKERS=1 P2D_H2D_HOST_COPY_WORKERS=1
export SGLANG_AGENTIC_KV_P2D_D2H_WORKERS=1 SGLANG_AGENTIC_KV_P2D_H2D_WORKERS=1
export RELAY_ENABLED=false P_READY_BACKPRESSURE_MODE=disabled
exec bash "${PD_ROOT}/scripts/new_method/run_4p4d_numa_case.sh"
